version: 2.1

jobs:
  generate_pdf:
    docker:
      - image: asciidoctor/docker-asciidoctor:1.41
    resource_class: small
    steps:
      - checkout
      - run:
          name: generate onboarding documentation - pdf
          command: asciidoctor-pdf *.adoc
      - run:
          name: moving artifacts
          command: |
            mkdir -p artifacts
            mv *.pdf artifacts
      - store_artifacts:
          path: artifacts

workflows:
  generate_pdf:
      when:
        equal: [ webhook, << pipeline.trigger_source >> ]
      jobs:
        - generate_pdf:
            pre-steps:
              - run:
                  name: update apk and install dependencies
                  command: apk update && apk add git-lfs openssh
